export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Minimalist Cashmere Blend Coat",
    slug: "minimalist-cashmere-blend-coat",
    price: 249.0,
    description: "A timeless coat crafted from a luxurious cashmere blend. Features a relaxed silhouette, notched lapels, and side pockets.",
    images: ["/hero.png"], // Reuse hero for now or generate more
    category: "Men",
    isNew: true,
    stock: 15,
  },
  {
    id: "2",
    name: "Silk Evening Gown",
    slug: "silk-evening-gown",
    price: 399.0,
    description: "Elegant silk evening gown with a flattering drape and delicate straps. Perfect for formal occasions.",
    images: ["/women.png"],
    category: "Women",
    isNew: false,
    stock: 5,
  },
  {
    id: "3",
    name: "Classic Wool Trousers",
    slug: "classic-wool-trousers",
    price: 129.0,
    description: "Tailored wool trousers with a clean, straight-leg cut. Versatile enough for office and casual wear.",
    images: ["/men.png"],
    category: "Men",
    isNew: false,
    stock: 20,
  },
  {
    id: "4",
    name: "Leather Chelsea Boots",
    slug: "leather-chelsea-boots",
    price: 189.0,
    description: "Premium leather boots with elasticated side panels and a pull tab. Durable and stylish.",
    images: ["/hero.png"],
    category: "Accessories",
    isNew: true,
    stock: 0,
  },
];
